version: '2'

services:

    scrum_web:
        build: ./source
        container_name: scrum_web 
        expose:
            - "8000"
        depends_on:
            - scrum_mysql
            - scrum_mysql_data
            - scrum_redis
            - scrum_rabbitmq
        links:
            - scrum_mysql:mysql
        volumes:
            - ./source:/usr/src/app
        env_file: .env
        environment:
            DEBUG: 'true'
        command: ./run_web.sh


    scrum_redis:
        image: redis:3.2
        container_name: scrum_redis


    scrum_rabbitmq:
        container_name: scrum_rabbitmq
        image: rabbitmq:3.6
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit_admin
            - RABBITMQ_DEFAULT_PASS=scrum@2016!
        ports:
            - "5672:5672"       # we forward this port because it's useful for debugging
            - "15672:15672"     # here, we can access rabbitmq management plugin                                                                


    scrum_celery_worker:
        build: ./source        
        volumes:
            - ./source:/usr/src/app
        depends_on:
            - scrum_mysql
            - scrum_mysql_data
            - scrum_redis
            - scrum_rabbitmq
        links:
            - scrum_rabbitmq:rabbitmq
        command: ./run_celery.sh


    scrum_nginx:
        build: ./nginx/
        container_name: scrum_nginx
        ports:
            - "9000:80"                                             # Host port 9000 is mapped on to container's port 80
        volumes:
            - ./source:/usr/src/app
        links:
            - scrum_web:web


    scrum_mysql_data:
        image: mysql:5.7
        container_name: scrum_mysql_data
        entrypoint: /bin/bash


    scrum_mysql:
        image: mysql:5.7
        container_name: scrum_mysql
        depends_on:
            - scrum_mysql_data
        volumes_from:
            - scrum_mysql_data
        environment:
            MYSQL_DATABASE: scrum_app
            MYSQL_USER: scrum_master
            MYSQL_PASSWORD: scrum@2016!
            MYSQL_ROOT_PASSWORD: Selenite#1